# django.yml
name: Run Django Tests
on:
  #push:
    #branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test-django-app:
    runs-on: ubuntu-latest

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
      - name: Run Django test
        run: |
          python manage.py test
