name: Linting

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements/dev.txt ]; then pip install -r requirements/dev.txt; fi
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py') --load-plugins pylint_django --django-settings-module=config.settings
